#!/usr/bin/env bash
# ==============================================================================
# Brum - Multi-Format Release Packaging Script
# Generates: Standalone Tarballs (.tar.gz), Debian (.deb), Alpine (.apk), and Checksums
# ==============================================================================

set -euo pipefail

VERSION=$(grep -m1 '^version = ' Cargo.toml | cut -d '"' -f2)
ARCH=$(uname -m)
DIST_DIR="./dist"

echo "======================================================"
echo "Building Brum Release Packages (v${VERSION})..."
echo "======================================================"

# 1. Compile Release Binary
echo "Compiling standalone release binary..."
cargo build --release

rm -rf "${DIST_DIR}"
mkdir -p "${DIST_DIR}"

# 2. Package Generic Tarball
TARBALL_NAME="brum-v${VERSION}-linux-${ARCH}"
TARBALL_DIR="/tmp/${TARBALL_NAME}"
rm -rf "${TARBALL_DIR}"
mkdir -p "${TARBALL_DIR}"

cp "./target/release/brum" "${TARBALL_DIR}/"
cp "./config.toml" "${TARBALL_DIR}/"
cp "./brum.service" "${TARBALL_DIR}/"
cp "./LICENSE" "${TARBALL_DIR}/"
cp "./README.md" "${TARBALL_DIR}/"
cp "./scripts/lxc-install.sh" "${TARBALL_DIR}/install.sh"

echo "📦 Creating ${TARBALL_NAME}.tar.gz..."
tar -czf "${DIST_DIR}/${TARBALL_NAME}.tar.gz" -C /tmp "${TARBALL_NAME}"

# 3. Build Debian .deb Package
DEB_DIR="/tmp/deb-pkg"
rm -rf "${DEB_DIR}"
mkdir -p "${DEB_DIR}/DEBIAN"
mkdir -p "${DEB_DIR}/usr/local/bin"
mkdir -p "${DEB_DIR}/etc/brum"
mkdir -p "${DEB_DIR}/lib/systemd/system"
mkdir -p "${DEB_DIR}/usr/share/pixmaps"
mkdir -p "${DEB_DIR}/usr/share/doc/brum"

cat << DEBEOF > "${DEB_DIR}/DEBIAN/control"
Package: brum
Version: ${VERSION}
Section: utils
Priority: optional
Architecture: amd64
Maintainer: Bolt J Woofson <bolt@boop.no>
Depends: ca-certificates, libsqlite3-0, libssh2-1, tar, bzip2, p7zip-full
Description: Multi-Pane Web Environment (File Commander/Manager)
 Blending the orthodox speed of Total Commander / Midnight Commander
 with the modern responsiveness of Next Explorer.
DEBEOF

cp "./target/release/brum" "${DEB_DIR}/usr/local/bin/"
cp "./config.toml" "${DEB_DIR}/etc/brum/config.toml"
cp "./brum.service" "${DEB_DIR}/lib/systemd/system/"
if [ -f "./assets/128/brum-128.webp" ]; then
    cp "./assets/128/brum-128.webp" "${DEB_DIR}/usr/share/pixmaps/brum.webp"
fi
cp "./LICENSE" "${DEB_DIR}/usr/share/doc/brum/copyright"
cp "./README.md" "${DEB_DIR}/usr/share/doc/brum/"

chmod 755 "${DEB_DIR}/usr/local/bin/brum"
chmod 755 "${DEB_DIR}/DEBIAN"

if command -v dpkg-deb >/dev/null 2>&1; then
    echo "📦 Building Debian .deb package..."
    dpkg-deb --build "${DEB_DIR}" "${DIST_DIR}/brum_${VERSION}_amd64.deb"
fi

# 4. Build Alpine Linux (.apk) Package
APK_DIR="/tmp/apk-pkg"
rm -rf "${APK_DIR}"
mkdir -p "${APK_DIR}/usr/local/bin"
mkdir -p "${APK_DIR}/etc/brum"
mkdir -p "${APK_DIR}/usr/share/pixmaps"
mkdir -p "${APK_DIR}/usr/share/applications"
mkdir -p "${APK_DIR}/usr/share/licenses/brum"
mkdir -p "${APK_DIR}/usr/share/doc/brum"

cp "./target/release/brum" "${APK_DIR}/usr/local/bin/"
cp "./config.toml" "${APK_DIR}/etc/brum/config.toml"
if [ -f "./assets/128/brum-128.webp" ]; then
    cp "./assets/128/brum-128.webp" "${APK_DIR}/usr/share/pixmaps/brum.webp"
fi
cp "./brum.desktop" "${APK_DIR}/usr/share/applications/"
cp "./LICENSE" "${APK_DIR}/usr/share/licenses/brum/"
cp "./README.md" "${APK_DIR}/usr/share/doc/brum/"

INSTALLED_SIZE=$(du -sb "${APK_DIR}" | cut -f1)
BUILD_DATE=$(date +%s)

cat << APKEOF > "${APK_DIR}/.PKGINFO"
# Generated by Brum release packaging
pkgname = brum
pkgver = ${VERSION}-r0
pkgdesc = Multi-Pane Web Environment (File Commander/Manager) - By Woofson
url = https://github.com/Woofson/brum
builddate = ${BUILD_DATE}
packager = Bolt J Woofson <bolt@boop.no>
size = ${INSTALLED_SIZE}
arch = ${ARCH}
origin = brum
license = MIT
depend = ca-certificates libssh2 sqlite-libs
APKEOF

echo "📦 Creating Alpine .apk package (brum-${VERSION}-r0.${ARCH}.apk)..."
tar -czf "${DIST_DIR}/brum-${VERSION}-r0.${ARCH}.apk" -C "${APK_DIR}" .PKGINFO usr etc

# 5. Generate SHA-256 Checksums
echo "🔒 Generating SHA-256 Checksums..."
(
    cd "${DIST_DIR}"
    rm -f SHA256SUMS SHA256SUMS.txt
    sha256sum * > SHA256SUMS
)

echo "======================================================"
echo "✅ Build Complete! Release artifacts generated in ./dist/:"
ls -la "${DIST_DIR}"
echo "======================================================"

